### ISSUE TITLE
start-machine-learning-in-2020

### ISSUE THREAD

**Issue by helshafaie46** [louisfb01/start-machine-learning-in-2020#1]

**Comment by helshafaie46** [comment]
Thanks so much

**Comment by paragonadey** [comment]
Thank you for your email, I have downloaded the material. Thanks so much I
appreciate.
Best regards
Paragon

**Comment by Roxelio44** [comment]
Why can't I open?

**Comment by helshafaie46** [comment]
Click on the title up there
